%% this script is used to plot the eigenvalues of the graph
clear all;
clear java;

% vec_path = 'D:/data/nek';
% vec_path = 'D:/projects/data/flow_entropy/3D';
vec_path = 'D:/data/flow_entropy/3D';
% vec_path = 'D:\data\flow_entropy\2D\isabel';
% vec_path = 'D:\data\nek';
% vec_path = 'D:\data\pnnl\smhagos';

    'source', ...
	'sink', ...
	'circle', ...
	'saddle', ...
	'electro', ...
	'equation', ...
	'tornado_swapped', ...
	'wrfout_d01_2007-10-01_18_00_00.t_1.d_1', ...
    ;
    'source.block_graph.block_8_8_8.weight_streamline', ...
    'circle.block_graph.block_8_8_8.weight_streamline', ...
    'saddle.block_graph.block_8_8_8.weight_streamline', ...
    'equation.block_graph.block_8_8_8.weight_streamline', ...
    'tornado_swapped.block_graph.block_8_8_8.weight_streamline', ...
    'wrfout_d01_2007-10-01_18_00_00.t_1.d_1.block_graph.block_30_30_9.weight_streamline', ...
    'plume.block_graph.block_32_32_32.weight_streamline', ...
%     'sink.block_graph.block_8_8_8.weight_streamline', ...
    ;

graph_names = {...
    'source.block_graph.block_8_8_8.weight_streamline', ...
    };

n_graphs = length(graph_names);

% th #eig values per iteration
max_n_eigs = 36; 

%% scan all vector fields
for graphi = 1:n_graphs
    graph_name = graph_names{graphi};
    
    script_apply_spectral_analysis_to_graph;
end

